# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QVIMtOYh1Kzzp-EeOptrh4t_UokdCazu
"""

import streamlit as st

def find_largest(a, b, c):
    largest = max(a, b, c)
    return largest

st.title("Find the largest among the 3 given numbers")

a = st.number_input("Enter the first number")
b = st.number_input("Enter the second number")
c = st.number_input("Enter the third number")

if st.button("Find the largest"):
    result = find_largest(a, b, c)
    st.write("The largest number is:", result)